apps/user_profile/urls.py
from django.conf.urls import url
from apps.user_profile.views import (
    RegisterFormView,
    UserPageView,
    child_form)

urlpatterns = [
    url(r'^register/$', RegisterFormView.as_view(), name="register"),
    url(r'^(?P<pk>[0-9]+)/$', UserPageView.as_view(), name="user-page"),
    url(r'^register_child/$', child_form, name='register_child'),
]

final_project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from apps.user_profile.views import signup, UserPageView
from final_project.views import MainPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', UserPageView.as_view(), name="user-page"),
    url(r'^kindergarten/', include('apps.kindergarten.urls')),
    url(r'^signup/$', signup, name='signup'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^$', MainPageView.as_view(), name="main"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

motrunich/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.MainPageView.as_view()),
    url(r'^first/$', views.FirstPageView.as_view()),
]

apps/user_profile/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.db import models
from django.utils.html import format_html
from apps.location.models import City
from core.models.helpers import image_path
from . import constants


class UserProfile(models.Model):
    SEX_CHOICES = (
        ('F', 'female'),
        ('M', 'male')
    )

    avatar = models.ImageField(
        upload_to=image_path,
        blank=True
    )
    address = models.CharField(
        max_length=255,
        blank=False,
        verbose_name='Адреса'
    )
    user = models.OneToOneField(
        to=User,
        related_name='profile'
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        blank=False,
        verbose_name='Стать'
    )
    phone = models.CharField(
        max_length=12,
        blank=True,
        unique=True,
        verbose_name='Номер телефону'
    )

    city = models.ForeignKey(
        to=City,
        null=True,
        default=None,
    )

    street = models.CharField(
        verbose_name='Вулиця',
        max_length=100,
        null=True,
        default=None,
    )

    house = models.PositiveIntegerField(
        verbose_name='Будинок',
        null=True,
        default=None,
    )

    house_symbol = models.CharField(
        verbose_name='Символ будинку',
        max_length=2,
        blank=True,
    )

    flat = models.PositiveIntegerField(
        verbose_name='Номер квартири',
        null=True,
        default=None,
    )

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        ordering = ('-id',)
        verbose_name = 'Профіль користувача'
        verbose_name_plural = 'Профілі користувачів'


class Child(models.Model):
    SEX_CHOICES = (
        ('F', 'female'),
        ('M', 'male')
    )
    PRIVILEGE_CHOICES = (
        (0, "---"),
        (1, constants.INVALID_CHILD),
        (1, constants.INVALID_CHILD_WITHOUT_CONTRAINDICATION),
        (1, constants.MILITARY_CHILD),
        (1, constants.ECO_CHILD),
        (1, constants.ORPHANS_CHILD)
    )
    privilege = models.PositiveIntegerField(
        default=0,
        choices=PRIVILEGE_CHOICES,
        verbose_name='Тип пільги дитини'
    )
    first_name = models.CharField(
        max_length=20,
        blank=False,
       verbose_name="Введіть ім'я",
    )
    last_name = models.CharField(
        max_length=40,
        blank=False,
        verbose_name="Введіть прізвище",
    )
    sure_name = models.CharField(
        max_length=20,
        blank=False,
        verbose_name="Введіть по-батькові",
    )
    dob = models.DateField(
        max_length=4,
        blank =False,
        verbose_name= "вік дитини",
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX_CHOICES,
        blank=False,
        verbose_name='Стать'
    )

    city = models.ForeignKey(
        to=City,
        null=True,
        default=None,
    )

    street = models.CharField(
        verbose_name='Вулиця',
        max_length=100,
        null=True,
        default=None,
    )

    house = models.PositiveIntegerField(
        verbose_name='Будинок',
        null=True,
        default=None,
    )

    flat = models.PositiveIntegerField(
        verbose_name='Номер квартири',
        null=True,
        default=None,
    )

    birth_sertificate_series = models.CharField(
        verbose_name='Серія свідотства про народження',
        max_length=100,
        null=True,
        default=None,

    )

    birth_sertificate_number = models.PositiveIntegerField(
        verbose_name='Номер свідотства',
        null=True,
        default=None,

    )

    birth_sertificate = models.CharField(
        verbose_name="Дані документу",
        max_length=255,
        null=True,
        default=None,

    )

    privilege_series = models.CharField(
        verbose_name='Серія документа',
        max_length=100,
        null=True,
        default=None,
        blank=True,
    )

    privilege_number = models.PositiveIntegerField(
        verbose_name='Номер документа',
        null=True,
        default=None,
        blank=True,
    )

    parents = models.ForeignKey(
        to=User,
        related_name='children',
        on_delete=models.CASCADE
    )

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Дитина'
        verbose_name_plural = 'Діти'

    def __str__(self):
        return 'Батьки:{} | {}'.format(
            self.parents.id,
            self.get_full_name()
        )

apps/user_profile/forms.py
from django import forms
from django.contrib.auth.models import User

from apps.kindergarten.models import Kindergarten
from apps.user_profile.models import Child


class RegisterChild(forms.Form):
    kindergarten = forms.ModelChoiceField(
        queryset=Kindergarten.objects.all(),
        required=True,
        widget=forms.HiddenInput()
    )

    child = forms.ModelChoiceField(
        queryset=Child.objects.all(),
        required=True
    )

class RegisterChildForm(forms.ModelForm):
    class Meta:
        model = Child
        fields = '__all__'

apps/user_profile/views.py
# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from django.views.generic import DetailView
from django.views.generic.edit import FormView


from apps.user_profile.forms import RegisterChildForm
from apps.user_profile.models import UserProfile, Child



class RegisterFormView(FormView):
    form_class = UserCreationForm
    template_name = "main_page/register.html"
    success_url = reverse_lazy('main')

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)


class UserPageView(DetailView):
    template_name = 'user_profile/user_page.html'
    model = UserProfile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['children'] = Child.objects.filter(parents=self.object)

        return context


def child_form(request):
    if request.method == 'POST':
        data = request.POST.copy()
        data['parents'] = request.user.id
        form = RegisterChildForm(data)
        if form.is_valid():
            form.save()
            return redirect(reverse('register_child'))
        return render(request, 'add_child.html', {'form': form})
    else:
        form = RegisterChildForm()
        return render(request, 'add_child.html', {'form': form})

templates/user_profile/user_page.html
{% extends 'base.html' %}

{% load static %}
{% block header %}
    <title>User Profile Page</title>
    <link href="{% static 'final_project/src/css/main_page.css' %}" rel="stylesheet">
{% endblock %}

{% block main %}

    <div class="container">
        <form  method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="inputName" class="control-label">Прізвище батька/матері</label>
                <input type="text" class="form-control" id="inputName" value="{{object.user.first_name}}">
            </div>

            <div class="form-group field-signupform-gender required">
                <label class="control-label" for="signupform-gender">Стать</label>
                <input id="signupform-gender" class="form-control" name="SignupForm[gender]" value="{{object.get_sex_display}}">
            </div>

            <div class="form-group">
                <label for="inputEmail" class="control-label">Ваша електронна пошта</label>
                <input type="email" class="form-control" id="inputEmail" value="{{object.user.email}}">
            </div>


            <div class="form-group field-signupform-phone1 required">
                <label class="control-label" for="signupform-phone1">Мобiльний телефон</label>
                <input type="text" id="signupform-phone1" value="{{object.phone}}" class="form-control">
            </div>

            <div class="form-group field-signupform-register_city required">
                <label class="control-label" for="signupform-register_city">Місто реєстрації (прописка)</label>
                <input type="text" id="signupform-register_city" class="form-control" name="SignupForm[register_city]"
                        value="{{object.city}}">
            </div>

            <div class="form-group field-signupform-register_street required">
                <label class="control-label" for="signupform-register_street">Вулиця реєстрації (прописка)</label>
                <input type="text" id="signupform-register_street" class="form-control"
                       name="SignupForm[register_street]" value="{{object.street}}">
            </div>

            <div class="form-group field-signupform-register_house required">
                <label class="control-label" for="signupform-register_house">Будинок реєстрації (прописка)</label>
                <input type="text" id="signupform-register_house" class="form-control"
                       name="SignupForm[register_house]" value="{{object.house}}">
            </div>

            <div class="form-group field-signupform-register_house_symbol">
                <label class="control-label" for="signupform-register_house_symbol">Символ будинку </label>
                <input type="text" id="signupform-register_house_symbol" class="form-control"
                       name="SignupForm[register_house_symbol]" value="{{ object.house_symbol }}">
            </div>

            <div class="form-group field-signupform-register_appart_number required">
                <label class="control-label" for="signupform-register_appart_number">Номер квартири реєстрації
                    (прописка)</label>
                <input type="text" id="signupform-register_appart_number" class="form-control"
                       name="SignupForm[register_appart_number]" value="{{object.flat}}">
            </div>

            <div class="form-group">
                <h3>Діти</h3>
                <ul>
                    {% for child in children %}
                    <li>{{ child.first_name }}  {{ child.last_name }}</li>
                    {% endfor %}
                </ul>


                <a href="http://127.0.0.1:8000/users/register_child/">
                   <button type="submit" class="btn btn-primary">Додати дитину</button>
                </a>

            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Зберегти</button>
            </div>


        </form>
    </div>

{% endblock %}